import React, { useState } from 'react';

export const TheCounterweight: React.FC = () => {
  const [activeTab, setActiveTab] = useState<'architecture' | 'testing' | 'security' | 'deploy'>('architecture');

  const comparisonData = {
    architecture: {
      vibe: {
        title: 'The Fragile Vibe-Code Trap',
        points: [
          'Uncontrolled LLM code generation with duplicate logic across files',
          'Implicit schemas, loose typing (`any` everywhere), and runtime crashes',
          'Zero state management contracts, leading to cascade re-renders and memory leaks',
          'Database migrations executed ad-hoc without rollbacks or constraints',
        ],
        codeSnippet: `// ❌ Fragile Vibe Code: No schema invariants, silent error swallow
async function handlePayment(req: any, res: any) {
  try {
    const data = req.body;
    await db.raw('UPDATE users SET balance = ' + data.amt); // SQL injection
    res.json({ ok: true });
  } catch (e) {
    console.log("error", e); // Silently fails, zero audit trail
  }
}`,
      },
      air: {
        title: 'Project AIR Institutional Engineering',
        points: [
          'Deterministic contract-first specifications validated across all boundaries',
          'Strict TypeScript & Rust type safety with zero runtime schema divergence',
          'State engines built with finite-state machine invariants',
          'Atomic transactional migrations with zero-downtime automated rollbacks',
        ],
        codeSnippet: `// ✅ Project AIR: Cryptographically validated, deterministic transaction
export const processPayment = async (
  ctx: ExecutionContext,
  input: PaymentContractInput
): Promise<Result<PaymentReceipt, PaymentError>> => {
  const validated = PaymentContractSchema.parse(input);
  return await ctx.db.transaction(async (tx) => {
    const auditLog = await tx.ledger.recordEntry({ ...validated, timestamp: ctx.now() });
    return Ok({ transactionId: auditLog.id, status: 'SETTLED' });
  });
};`,
      },
    },
    testing: {
      vibe: {
        title: 'Vibe-Code Testing Illusion',
        points: [
          'Zero automated tests or shallow snapshot tests generated by LLMs',
          'Green tests that pass even when critical domain business logic is deleted',
          'Zero edge-case coverage: fails under concurrent load or network jitter',
          'Manual clicking in browser used as "QA verification"',
        ],
        codeSnippet: `// ❌ Vibe Code Test: Passing test that verifies nothing
test("user works", () => {
  const user = { id: 1 };
  expect(user.id).toBe(1); // Meaningless assertion; business logic untracked
});`,
      },
      air: {
        title: 'Project AIR Deterministic Mutation Testing',
        points: [
          'Automated AST mutation testing (Stryker engine) killing 100% of injected faults',
          'Property-based fuzzing testing invariants across 500,000 randomized state runs',
          'Hermetic database test containers for authentic concurrent race-condition checks',
          'Deterministic replay harness reproducing any production anomaly in CI',
        ],
        codeSnippet: `// ✅ Project AIR: Property-based invariant & mutation test
describe('Ledger Invariants · Stryker Mutation Gate', () => {
  it('must kill mutants attempting overdraft balance mutations', async () => {
    await fc.assert(
      fc.asyncProperty(arbitraryLedgerOperations(), async (operations) => {
        const state = await simulateLedgerExecution(operations);
        expect(state.totalDeposits).toBe(state.totalLiabilities + state.retainedBalance);
      })
    );
  });
});`,
      },
    },
    security: {
      vibe: {
        title: 'Vibe-Code Security Exposure',
        points: [
          'Vulnerable npm dependencies with unvetted CVEs pulled into build',
          'Hardcoded API keys, exposed database connection strings in client bundles',
          'Missing role-based access control (RBAC) checks on internal endpoints',
          'Zero audit logging or tamper-evident request trails',
        ],
        codeSnippet: `// ❌ Vibe Code: Client-side secret exposure & insecure auth
const SUPABASE_SERVICE_ROLE_KEY = "eyJhbGciOi..."; // Leaked secret in client
export async function deleteOrg(orgId: string) {
  await fetch('/api/delete?id=' + orgId); // Anyone can call, no RBAC check
}`,
      },
      air: {
        title: 'Project AIR Security Hardening Standard',
        points: [
          'Zero-CVE policy enforced through hermetic static analysis in CI',
          'Zero secrets client-side; cryptographic server proxy routing',
          'Strict tenant isolation with row-level security and cryptographically signed JWTs',
          'Tamper-evident structured audit logging for SOC2 / ISO 27001 readiness',
        ],
        codeSnippet: `// ✅ Project AIR: Zero-Trust RBAC & Tamper-Evident Access
export const authorizeOrgDeletion = (session: Session, orgId: OrgId): AuthorizationDecision => {
  if (!session.hasPermission(Permissions.ORG_DESTROY, orgId)) {
    return Deny('UNAUTHORIZED_TENANT_ACCESS', { actor: session.userId, target: orgId });
  }
  return Allow();
};`,
      },
    },
    deploy: {
      vibe: {
        title: 'Vibe-Code Deployment Drift',
        points: [
          'Manual deployment scripts running on unmanaged single-server instances',
          'Downtime during updates, schema desync causing runtime 500 errors',
          'Zero rollback strategy if a bug escapes to production',
          'No automated health checks, memory leak monitoring, or alerts',
        ],
        codeSnippet: `// ❌ Vibe Code: Manual ssh deploy, downtime guaranteed
# bash deploy.sh
git pull
npm run build # build fails on server, site goes down for 4 hours
pm2 restart app`,
      },
      air: {
        title: 'Project AIR Zero-Downtime Infrastructure',
        points: [
          'Immutable infrastructure defined in Terraform with hermetic container builds',
          'Blue/Green deployment with zero-downtime traffic switching',
          'Automated health probes verifying schema migrations before traffic cutover',
          'Instant 1-click or automated rollback upon any metric regression',
        ],
        codeSnippet: `// ✅ Project AIR: Automated Blue/Green Traffic Gate
resource "google_cloud_run_v2_service" "api" {
  traffic {
    type     = "TRAFFIC_TARGET_ALLOCATION_TYPE_REVISION"
    percent  = 100
    revision = var.verified_hermetic_revision
  }
}`,
      },
    },
  };

  const current = comparisonData[activeTab];

  return (
    <section id="the-counterweight" className="py-20 border-b border-white/10 px-4 sm:px-8 lg:px-12 max-w-7xl mx-auto">
      {/* Section Header */}
      <div className="flex flex-col md:flex-row md:items-end justify-between mb-12">
        <div>
          <div className="flex items-center space-x-2 text-xs font-mono text-[#3FD6D6] uppercase tracking-wider mb-2">
            <span>01 · THE COUNTERWEIGHT</span>
            <span>·</span>
            <span className="text-slate-400">MARKET WEDGE & POSITIONING</span>
          </div>
          <h2 className="font-display font-bold text-2xl sm:text-4xl text-white tracking-tight text-balance">
            The counterweight to fragile "vibe-coded" prototypes.
          </h2>
        </div>
        <p className="mt-4 md:mt-0 text-sm font-body text-slate-400 max-w-md">
          AI coding assistants are brilliant at writing snippets, but devastating at maintaining systems.
          We engineer the deterministic foundation required for enterprise scale.
        </p>
      </div>

      {/* The Empirical Shock Metrics */}
      <div className="mb-12 grid grid-cols-1 md:grid-cols-3 gap-6">
        <div className="obsidian-card p-6 rounded-lg border border-white/10 relative overflow-hidden">
          <div className="text-xs font-mono text-slate-400 mb-2 uppercase">Market Reality</div>
          <div className="font-mono text-3xl sm:text-4xl font-bold text-white tabular-nums">41%</div>
          <p className="text-xs text-slate-400 mt-2 leading-relaxed">
            Of modern software is now generated by AI models without human architectural verification.
          </p>
        </div>

        <div className="obsidian-card p-6 rounded-lg border border-white/10 relative overflow-hidden">
          <div className="text-xs font-mono text-[#FF7A4D] mb-2 uppercase">The Churn Multiplier</div>
          <div className="font-mono text-3xl sm:text-4xl font-bold text-[#FF7A4D] tabular-nums">+39%</div>
          <p className="text-xs text-slate-400 mt-2 leading-relaxed">
            Higher code churn, regression rates, and rewritten lines in AI-assisted codebases within 6 months.
          </p>
        </div>

        <div className="obsidian-card p-6 rounded-lg border border-white/10 relative overflow-hidden">
          <div className="text-xs font-mono text-[#3FD6D6] mb-2 uppercase">The AIR Invariant</div>
          <div className="font-mono text-3xl sm:text-4xl font-bold text-[#3FD6D6] tabular-nums">100%</div>
          <p className="text-xs text-slate-400 mt-2 leading-relaxed">
            Mutation test coverage and deterministic contracts. Code cannot ship if a test doesn't kill synthetic bugs.
          </p>
        </div>
      </div>

      {/* Interactive Tabs */}
      <div className="flex flex-wrap items-center gap-2 mb-6 border-b border-white/10 pb-4">
        {[
          { id: 'architecture', label: '01. Architecture & Contracts' },
          { id: 'testing', label: '02. Deterministic Testing' },
          { id: 'security', label: '03. Security & RBAC' },
          { id: 'deploy', label: '04. Deployment & Infrastructure' },
        ].map((tab) => (
          <button
            key={tab.id}
            onClick={() => setActiveTab(tab.id as any)}
            className={`px-4 py-2 rounded text-xs font-mono tracking-wider transition-all cursor-pointer ${
              activeTab === tab.id
                ? 'bg-white text-[#0A0D12] font-semibold'
                : 'text-slate-400 hover:text-white hover:bg-white/[0.04]'
            }`}
          >
            {tab.label}
          </button>
        ))}
      </div>

      {/* Side-by-Side Comparison Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Fragile Vibe Code Column */}
        <div className="p-6 rounded-lg bg-red-950/10 border border-red-500/20 flex flex-col justify-between">
          <div>
            <div className="flex items-center justify-between pb-3 border-b border-red-500/20 mb-4">
              <span className="font-mono text-xs text-[#FF7A4D] uppercase font-semibold">
                ⚠️ THE VIBE-CODE TRAP
              </span>
              <span className="text-[11px] font-mono text-slate-500">PROTOTYPE ILLUSION</span>
            </div>
            <h3 className="font-display font-semibold text-lg text-white mb-3">
              {current.vibe.title}
            </h3>
            <ul className="space-y-2 mb-6">
              {current.vibe.points.map((pt, i) => (
                <li key={i} className="text-xs text-slate-300 flex items-start space-x-2">
                  <span className="text-[#FF7A4D] font-mono font-bold mt-0.5">✕</span>
                  <span>{pt}</span>
                </li>
              ))}
            </ul>
          </div>
          <div className="mt-4 pt-4 border-t border-red-500/15">
            <pre className="p-3 bg-black/60 rounded font-mono text-[11px] text-red-300/90 overflow-x-auto leading-relaxed">
              <code>{current.vibe.codeSnippet}</code>
            </pre>
          </div>
        </div>

        {/* Project AIR Institutional Engineering Column */}
        <div className="p-6 rounded-lg bg-[#007C87]/10 border border-[#3FD6D6]/30 flex flex-col justify-between shadow-xl">
          <div>
            <div className="flex items-center justify-between pb-3 border-b border-[#3FD6D6]/20 mb-4">
              <span className="font-mono text-xs text-[#3FD6D6] uppercase font-semibold">
                🛡️ PROJECT AIR STANDARD
              </span>
              <span className="text-[11px] font-mono text-[#3FD6D6]/80">DETERMINISTIC RIGOR</span>
            </div>
            <h3 className="font-display font-semibold text-lg text-white mb-3">
              {current.air.title}
            </h3>
            <ul className="space-y-2 mb-6">
              {current.air.points.map((pt, i) => (
                <li key={i} className="text-xs text-slate-200 flex items-start space-x-2">
                  <span className="text-[#3FD6D6] font-mono font-bold mt-0.5">✓</span>
                  <span>{pt}</span>
                </li>
              ))}
            </ul>
          </div>
          <div className="mt-4 pt-4 border-t border-[#3FD6D6]/20">
            <pre className="p-3 bg-black/70 rounded font-mono text-[11px] text-[#3FD6D6] overflow-x-auto leading-relaxed border border-[#3FD6D6]/20">
              <code>{current.air.codeSnippet}</code>
            </pre>
          </div>
        </div>
      </div>
    </section>
  );
};
